/**
 * `/llms.txt`, shown in a dialog instead of as a page navigation.
 *
 * llms.txt (https://llmstxt.org) is a convention for serving a curated plain-text
 * version of a site so language models read prose rather than scraping markup.
 * Ours is generated from `src/data/profile.js` at build time, and fetched here, so
 * what a visitor reads is byte-for-byte what a crawler gets — and reading it never
 * takes them off the page.
 */

import { useEffect, useRef, useState } from "react";
import { motion } from "framer-motion";
import { FaCheck, FaCopy } from "react-icons/fa";
import MacWindow from "./MacWindow";

export default function LlmsDialog({ onClose }) {
  const [text, setText] = useState(null);
  const [failed, setFailed] = useState(false);
  const [copied, setCopied] = useState(false);
  const copyTimer = useRef(null);

  useEffect(() => {
    const controller = new AbortController();
    fetch("/llms.txt", { signal: controller.signal })
      .then((res) => {
        if (!res.ok) throw new Error(String(res.status));
        return res.text();
      })
      .then(setText)
      .catch((error) => {
        if (error.name !== "AbortError") setFailed(true);
      });
    return () => controller.abort();
  }, []);

  useEffect(() => {
    const onKey = (event) => event.key === "Escape" && onClose();
    window.addEventListener("keydown", onKey);
    return () => window.removeEventListener("keydown", onKey);
  }, [onClose]);

  useEffect(() => () => clearTimeout(copyTimer.current), []);

  const copy = async () => {
    if (!text) return;
    try {
      await navigator.clipboard.writeText(text);
      setCopied(true);
      copyTimer.current = setTimeout(() => setCopied(false), 2000);
    } catch {
      setFailed(true);
    }
  };

  return (
    <div
      className="fixed inset-0 z-[9997] flex items-center justify-center bg-black/50 p-3 backdrop-blur-sm sm:p-6"
      onClick={onClose}
      role="presentation"
    >
      <motion.div
        initial={{ opacity: 0, scale: 0.96, y: 12 }}
        animate={{ opacity: 1, scale: 1, y: 0 }}
        transition={{ type: "spring", stiffness: 320, damping: 28 }}
        className="w-full max-w-3xl"
        // Clicks inside must not reach the backdrop's close handler.
        onClick={(event) => event.stopPropagation()}
      >
        <MacWindow title="/llms.txt" onClose={onClose}>
          <div className="relative">
            <button
              type="button"
              onClick={copy}
              disabled={!text}
              className="absolute right-3 top-3 flex items-center gap-1.5 rounded-md bg-white/10 px-2.5 py-1.5 text-[11px] font-bold text-slate-200 backdrop-blur transition hover:bg-white/20 disabled:opacity-40"
            >
              {copied ? <FaCheck className="text-[#27C841]" /> : <FaCopy />}
              {copied ? "Copied" : "Copy"}
            </button>

            <pre className="max-h-[70vh] overflow-auto bg-[#0f1115] p-4 pt-14 font-mono text-[11px] leading-relaxed text-slate-300 sm:p-5 sm:pt-14 sm:text-[11.5px]">
              {text ??
                (failed
                  ? "Could not load /llms.txt. It is generated by `npm run llms` — run that, or `npm run build`, and reload."
                  : "loading /llms.txt…")}
            </pre>
          </div>
        </MacWindow>
      </motion.div>
    </div>
  );
}
