/**
 * Surfaces `/llms.txt` on the page instead of leaving it as an invisible file.
 *
 * llms.txt (https://llmstxt.org) is a convention for serving a curated,
 * plain-text version of a site so language models read prose rather than
 * scraping markup. Ours is generated from `src/data/profile.js` at build time,
 * and fetched here so what visitors read is byte-for-byte what a crawler gets.
 */

import { useEffect, useRef, useState } from "react";
import { FaCopy, FaCheck, FaExternalLinkAlt } from "react-icons/fa";
import MacWindow from "./MacWindow";
import SectionHeading from "./SectionHeading";

export default function LlmsSection() {
  const [text, setText] = useState(null);
  const [failed, setFailed] = useState(false);
  const [copied, setCopied] = useState(false);
  const copyTimer = useRef(null);

  useEffect(() => {
    const controller = new AbortController();
    fetch("/llms.txt", { signal: controller.signal })
      .then((res) => {
        if (!res.ok) throw new Error(String(res.status));
        return res.text();
      })
      .then(setText)
      .catch((error) => {
        if (error.name !== "AbortError") setFailed(true);
      });
    return () => controller.abort();
  }, []);

  useEffect(() => () => clearTimeout(copyTimer.current), []);

  const copy = async () => {
    if (!text) return;
    try {
      await navigator.clipboard.writeText(text);
      setCopied(true);
      copyTimer.current = setTimeout(() => setCopied(false), 2000);
    } catch {
      setFailed(true);
    }
  };

  return (
    <section id="llms" className="scroll-mt-24 py-16">
      <SectionHeading dotColor="#5ee7df">llms.txt</SectionHeading>
      <p className="mt-2 max-w-2xl text-slate-500">
        Everything on this page, as clean plain text at{" "}
        <a
          href="/llms.txt"
          className="font-semibold text-[#006AFF] underline decoration-dotted"
          target="_blank"
          rel="noreferrer noopener"
        >
          /llms.txt
        </a>
        . It is generated from the same data file that renders this site, so an LLM asked about me
        reads curated prose rather than scraped markup — and it can never drift out of date.
      </p>

      <MacWindow
        title="/llms.txt"
        className="mt-6"
        onZoom={() => window.open("/llms.txt", "_blank", "noopener")}
      >
        <div className="relative">
          <div className="absolute right-3 top-3 flex gap-2">
            <button
              type="button"
              onClick={copy}
              disabled={!text}
              className="flex items-center gap-1.5 rounded-md bg-white/10 px-2.5 py-1.5 text-[11px] font-bold text-slate-200 backdrop-blur transition hover:bg-white/20 disabled:opacity-40"
            >
              {copied ? <FaCheck className="text-[#27C841]" /> : <FaCopy />}
              {copied ? "Copied" : "Copy"}
            </button>
            <a
              href="/llms.txt"
              target="_blank"
              rel="noreferrer noopener"
              className="flex items-center gap-1.5 rounded-md bg-white/10 px-2.5 py-1.5 text-[11px] font-bold text-slate-200 backdrop-blur transition hover:bg-white/20"
            >
              <FaExternalLinkAlt /> Open
            </a>
          </div>

          <pre className="max-h-96 overflow-auto bg-[#0f1115] p-5 pt-14 font-mono text-[11.5px] leading-relaxed text-slate-300">
            {text ??
              (failed
                ? "Could not load /llms.txt. It is generated by `npm run llms` — run that, or `npm run build`, and reload."
                : "loading /llms.txt…")}
          </pre>
        </div>
      </MacWindow>
    </section>
  );
}
